### ISSUE TITLE
The implementation of `Debug` breaks build on Rust 1.1

### ISSUE THREAD

**Issue by fiveop** [rust-lang-nursery/tempdir#14]
The commit 7874626286e5e22adbf764b7ec2e7cd6daa6b587 broke the build on Rust 1.1. I do not mind, however, I wanted to have it documented somewhere.

**Comment by brson** [comment]
Thanks for reporting this! cc @alexcrichton

**Comment by brson** [comment]
I have no idea offhand why this would be...

**Comment by alexcrichton** [comment]
@brson I believe it's because the debug builders were added after Rust 1.1

@fiveop right now the nursery crates defacto support at least the last two stable versions of Rust, but beyond that there's no guarantees provided currently.

**Comment by brson** [comment]
Oh huh. I read "1.11" not "1.1". That's pretty old!

**Comment by brson** [comment]
I doubt anybody will ever be motivated to fix this.
