### ISSUE TITLE
TempDir affected by remove_dir_all unreliability on windows

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/tempdir#15]
I have test cases where TempDir fails to remove the directory mysteriously and irregularly.

cc https://github.com/rust-lang/rust/issues/29497

**Comment by brson** [comment]
To fix this I'd suggest extracting the robust remove_dir_all impl from [this unmerged PR](https://github.com/rust-lang/rust/pull/31944/files), along with its test cases, and publishing it to crates.io, then updating TempDir to use that.

@alexcrichton does that sound reasonable to you?

**Comment by alexcrichton** [comment]
Sounds reasonable to me!

**Comment by XAMPPRocky** [comment]
I'd like to take this one on if that's alright?

**Comment by brson** [comment]
@Aaronepower Yes!

**Comment by brson** [comment]
There's an open but unfinished PR for this. What I'd like to happen yet:

- Move the code into a remove_dir_all_crate
- Write tests that capture that it works on windows in tricky cases [cribbed from this issue](https://github.com/rust-lang/rust/issues/29497).
- Use winapi instead of duplicating windows definitions
- Fix tempdir

**Comment by XAMPPRocky** [comment]
Yeah sorry, I had a winapi implementation however it was wrong, it failed the tests. And then I moved my main development over to macOS so it fell by the wayside. I plan to see if I can finish this over the weekend.

**Comment by brson** [comment]
Thanks @Aaronepower ! 😍
