### ISSUE TITLE
Unnecessary Option in TempDir or panicky code

### ISSUE THREAD

**Issue by lilianmoraru** [rust-lang-nursery/tempdir#21]
`TempDir` currently looks like this:
```rust
pub struct TempDir {
    path: Option<PathBuf>,
}
```
And functions rely on it being an `Option`, ex:
```rust
pub fn path(&self) -> &path::Path {
    self.path.as_ref().unwrap()
}
// and
pub fn into_path(mut self) -> PathBuf {
    self.path.take().unwrap()
}
```
These functions do not take into consideration that the `path` could be set to `None`.
Currently this is not a problem because `fn new_in` will never set it to `None` however many times it will retry to find a random folder name.
So, the result is either `path`(from `TempDir`) being set to `Some(path)` or the user receiving `Err`.
In this case, why not get rid of the `Option` and just set the `TempDir { path: }` directly to `path` and return `Err` otherwise?

If `None` is planned for feature use, than functions like `path` and `into_path` should probably return `Option<&path::Path>` and `Option<PathBuf>` instead of `unwrap`ping for the user and panicking.

This of course will bump the library version.

**Comment by dtolnay** [comment]
The Option\<PathBuf> is what makes into_path possible to implement. See [`E0509`](https://doc.rust-lang.org/error-index.html#E0509) which prohibits moving a value out of a Drop type.

```diff
  pub struct TempDir {
-     path: Option<PathBuf>,
+     path: PathBuf,
  }

  pub fn into_path(mut self) -> PathBuf {
-     self.path.take().unwrap()
+     self.path                   // this is not allowed
  }
```

Ownership is used to ensure that the unwrap() calls can never panic. If you hit a case that does panic in unwrap(), please report it as a bug.

**Comment by lilianmoraru** [comment]
@dtolnay Thanks. The error explains it very well why this is needed.
No issues then :smile: 
I close it.
