### ISSUE TITLE
Finalize conventions for `close`

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/tempdir#26]
There's no precedent in std for this, and there's been suggestion that the current signature is not correct (preferring `&mut self` to `self`).

**Comment by brson** [comment]
In this case also the 'close' name may not be descriptive enough, since we're not just closing a resource, but deleting it.

**Comment by opilar** [comment]
@brson so `close` method should be named to `remove`?

**Comment by opilar** [comment]
Seems just `drop` does what we need. I think it would be better to merge `close` method into `drop`.

**Comment by brson** [comment]
@opilar So the issue here is that sometimes it's appropriate to close a resource explicitly, and not let it implicitly drop. Usually this is to handle an error condition, which drop doesn't allow.

Types in std don't generally have close methods, but they should, and the conventions aren't decided, so for this issue we need to decide what we want such 'close' conventions to be, and whether the existing method here conforms to them. Design question. Not sure how to resolve it, but it probably needs to be a broader discussion elsewhere. cc @dtolnay

**Comment by dtolnay** [comment]
Yep, this came up during our `flate2` review where they use a confusing system of [`finish`](https://docs.rs/flate2/0.2.19/flate2/write/struct.DeflateEncoder.html#method.finish) + [`flush_finish`](https://docs.rs/flate2/0.2.19/flate2/write/struct.DeflateEncoder.html#method.flush_finish) + [`try_finish`](https://docs.rs/flate2/0.2.19/flate2/write/struct.DeflateEncoder.html#method.try_finish). I filed https://github.com/brson/rust-api-guidelines/issues/61 to follow up with a guideline for checked teardown that would apply to flate2, tempdir, and hopefully everything else.

**Comment by brson** [comment]
Still no clear guidelines.

**Comment by brson** [comment]
I believe the current definition of `Tempdir::close` of `close(self) -> Result<()>` is correct for this crate, per my argument [here](https://github.com/brson/rust-api-guidelines/issues/61#issuecomment-313279887).

I don't think there is any reasonable case for retrying a failed close here.

**Comment by alexcrichton** [comment]
I [posted a longer comment](https://github.com/brson/rust-api-guidelines/issues/61#issuecomment-315786044) on the tracking issue, but I'd personally still feel that `&mut self` is more appropriate.

**Comment by brson** [comment]
@alexcrichton's comments in the linked thread about favoring `&mut self`  for `close` I find fairly convincing in the general case. At least it seems that `&mut self` composes better if there are lots of fallible destructors in play, at the expense of maintaining more state.

**Comment by KodrAus** [comment]
When combining the `tempdir` and `tempfile` APIs in https://github.com/Stebalien/tempfile/pull/33 we kept the close method as-is, which is consistent with the equivalent close methods on temporary files.

We still haven't reached much consensus in https://github.com/rust-lang-nursery/api-guidelines/issues/61, but can continue the discussion there about the general merits of different approaches to checked teardown.

Thanks all!
