### ISSUE TITLE
Support randomly-named directories

### ISSUE THREAD

**Issue by Susurrus** [rust-lang-nursery/tempdir#35]
When writing tests that need a working directly I've used randomly-named directories a lot. The Python equivalent of `tempdir` does that by default. I was thinking of the addition of `tempdir::new_unique()` that would generate a new unique temporary directory.

**Comment by steveklabnik** [comment]
I may be missing something, but the argument to `new` is only a prefix, right? So it does this already. If you didn't want a prefix, you could keep it empty. https://doc.rust-lang.org/tempdir/src/tempdir/lib.rs.html#202

**Comment by Susurrus** [comment]
@steveklabnik Sorry! I skimmed the intro and didn't see the part that said that. And then I looked at the docs for `new()` and they didn't say anything about generating a filename randomly. That comboed with the fact that the argument isn't an `Option<&str>` is why I thought it didn't generate random directory names. Maybe the docs for `new()` can be extended to provide a little more details?

**Comment by KodrAus** [comment]
We've moved the `tempdir` API into [`tempfile`](https://github.com/Stebalien/tempfile). One of the changes was to remove the `prefix` argument from `TempDir::new()` and use a builder to specify a prefix/suffix so I'll go ahead and close this one now. Thanks all!
