### ISSUE TITLE
path to 1.0

### ISSUE THREAD

**Issue by Susurrus** [rust-lang-nursery/tempdir#38]
Ive been going through our dependencies and I saw that this crate is pre-1.0 and also didn't have a tracking issue for getting there. I wanted to post this to see if there was a plan for getting to 1.0. Considering how few issues have been posted with this crate and how often it's used, I'd think it would be pretty close to a 1.0, so wanted to check in here to see what the maintainers think.

**Comment by danielpclark** [comment]
See #28

**Comment by Susurrus** [comment]
Sorry, was looking for it in the title.
