### ISSUE TITLE
Deref and Into

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang-nursery/tempdir#4]
Did you consider implementing `Deref<Target=Path>` and `Into<PathBuf>` instead of the methods `into_path()` and `path()` ?

**Comment by alexcrichton** [comment]
We don't want to implement `Deref` as it's far too powerful for this situation, but implementing `Into` should be fine! This is just copied from the very old in-tree implementation and when it was written the conversion traits didn't exist.

Feel free to submit a PR adding the `Into` impl!
