### ISSUE TITLE
Support ramfs through type `RamDir`

### ISSUE THREAD

**Issue by vitiral** [rust-lang-nursery/tempdir#42]
I'm curious whether `tempdir` would be interested in adding a `RamDir` type if it were possible to make such a type.

[tmpfs](https://wiki.archlinux.org/index.php/tmpfs) is:

> tmpfs is a temporary filesystem that resides in memory and/or swap partition(s). Mounting directories as tmpfs can be an effective way of speeding up accesses to their files, or to ensure that their contents are automatically cleared upon reboot. 

It looks like there is a (linux only) [libmount](https://github.com/tailhook/libmount) that could be leveraged to do the job, although I would prefer using [ramfs](https://www.kernel.org/doc/Documentation/filesystems/ramfs-rootfs-initramfs.txt), as it is guaranteed to be in ram. I haven't looked at that crate, but `ramfs` could potentially be added there.

It's also at least _theoretically_ possible to support windows, as a tool exists called [ImDisk](http://www.ltr-data.se/opencode.html/#ImDisk), but this issue is suggesting unix-only support through the `tmpfs` call (for now).

This issue is mostly to ask whether this feature would be supported by the project devs or whether a new crate should be made instead. Thanks!

**Comment by KodrAus** [comment]
Hi @vitiral! This is an interesting idea. I think a separate crate is probably the best place to start because of the potential difficulty in cross-platform support, and because I think an in-memory fs is a useful thing in its own right with some separate use-cases to just probably-temporary directories on disk.

**Comment by vitiral** [comment]
that sounds good
