### ISSUE TITLE
deprecate into_path(), rename persist()

### ISSUE THREAD

**Issue by vitiral** [rust-lang-nursery/tempdir#44]
## Feature Request

This is a feature/API change request to rename [`into_path()`](https://docs.rs/tempdir/0.3.6/tempdir/struct.TempDir.html#method.into_path) to `persist()`, while deprecating `into_path()`.

## Reasoning
While I understand the logic behind calling it `into_path()` (since it "converts" the temporary directory into an "ordinary path"), `into_path()` actually performs an _action_ from the programmers point of view, namely it removes the invariant that the temporary directory will be deleted on `drop`.

This is made even more confusing by the documentation, which says: "This destroys the TempDir without deleting the directory represented by the returned Path." -- from a lingual point of view it sounds like we are destroying the directory

## Solution
```
/// Consumes the `TempDir` object without deleting the directory, 
/// returning the `PathBuf` where it is located.
///
/// The directory will no longer be automatically deleted.
fn persist(self) -> PathBuf { self.into_path() }
```

**Comment by vitiral** [comment]
For reference: the [`ergo_fs::PathTmp`](https://docs.rs/ergo_fs/0.1.5/ergo_fs/struct.PathTmp.html#method.persist) object (which wraps TempDir) has `persist()` instead of `into_path()`. If my reasonng is in error then it would be good for me to know while the library is still young!

**Comment by KodrAus** [comment]
Hi @vitiral!

We're actually moving the `tempdir` API into the [`tempfile` crate](https://github.com/Stebalien/tempfile) so folks can have consistent temporary files and directories. That work [has just been merged in](https://github.com/Stebalien/tempfile/pull/33).

Personally, I think `persist` is a better name, and is consistent with `tempfile::NamedTempFile::persist`.

Would you like to open this issue on the `tempfile` repo?

**Comment by vitiral** [comment]
done! See the linked issue.

I didn't know about `tempfile` -- I will make sure it gets used in `ergo_fs` as well!

**Comment by KodrAus** [comment]
Thanks! Since we've got https://github.com/Stebalien/tempfile/issues/42 to track this now I'll close the issue here.
