### ISSUE TITLE
Deprecate the tempdir crate

### ISSUE THREAD

**Issue by KodrAus** [rust-lang-nursery/tempdir#45]
In https://github.com/Stebalien/tempfile/pull/33 we combined the `tempdir` and `tempfile` APIs, with the goal of using the `tempfile` crate as the source of temporary files and directories going forward.

I've gone through and review the open issues here (and basically just closed them all). I think the next step is to propose deprecating this repository and moving into `rust-lang-deprecated`, with a note in the readme that `tempfile` is the place to go for temporary directories going forward.

What do you all think? Is there anything else we should consider?

**Comment by steveklabnik** [comment]
Is there any way we can signal this change to users? If I hadn't been subscribed here, I'd have had no idea.

**Comment by KodrAus** [comment]
Yeh, we'll definitely need to do that, I was hoping we could wait until there's a published version of `tempfile` folks can immediately get before we do though.

Maybe we can add a notice to the readme here now pointing users wanting to open issues to `tempfile` but note that `tempdir 0.3.6` is still available in the meantime?

@Stebalien do you have a plan in mind for the next release of `tempfile`? It would need to be a `3.0.0` wouldn't it, unless we go back and deprecate/shim the changed APIs on `NamedTempFile`.

**Comment by Stebalien** [comment]
Yes, it would need a 3.0.0. Issue here: https://github.com/Stebalien/tempfile/issues/43

**Comment by Stebalien** [comment]
3.0.0 has been released.

**Comment by KodrAus** [comment]
Awesome! This is exciting news!

So the next steps would be to shift this repository into the `deprecated` org, and put out some comms pointing folks to `tempfile`.

@Stebalien Were you planning to do a release announcement for the new version for `tempfile`?

**Comment by Stebalien** [comment]
So... Those usually go on reddit but I managed to lose my reddit password and have found that I *really* don't make another account (I spend enough time just reading reddit as it is).

Given that you did 99% of the work in this endeavor, want to make the announcement?

**Comment by KodrAus** [comment]
No problem :+1: I'll put something together along with a note about the `tempdir` deprecation and put it out tomorrow.

**Comment by KodrAus** [comment]
The [announcement has been posted](https://www.reddit.com/r/rust/comments/8dj1br/announcing_tempfile_30_now_featuring_temp/)!

I'll work on the RFC to shift `tempdir` into the `deprecated` organisation.

**Comment by KodrAus** [comment]
:) I just came here to write an RFC for shifting into the deprecated org and found it was already here! I'll go ahead and close this one now.

**Comment by jethrogb** [comment]
@KodrAus as you correctly note an RFC is required for deprecation. This crate should be moved back to the nursery until such a time as deprecation has been approved.

**Comment by KodrAus** [comment]
@jethrogb What exactly do you hope to achieve by returning `tempdir` to the nursery?
